scrape_configs:
   - job_name: 'otel-collector'
     scrape_interval: 3s
     static_configs:
       - targets: ['otel:8889']
       - targets: ['otel:8888']

   - job_name: 'rest'
     scrape_interval: 5s
     static_configs:
     - targets:
        - 'bilbo:9464'
       labels:
         group: "coolstore"


   - job_name: 'rest2'
     scrape_interval: 5s
     static_configs:
     - targets:
         - 'localhost:9464'
       labels:
         group: "coolstore"
        
   - job_name: 'rests'
     scrape_interval: 5s
     static_configs:
     - targets:
         - 'rest:8000'
       labels:
         group: "coolstore"


   - job_name: 'rests2'
     scrape_interval: 5s
     static_configs:
     - targets:
         - 'localhost:8000'
       labels:
         group: "coolstore"

   - job_name: 'OpenTelemetryTest'
     scrape_interval: 1s # poll very quickly for a more responsive demo
     static_configs:
     - targets: ['localhost:9184']